# netlify.toml
[[redirects]]
from = '/order/*'
to = 'https://sazito.com:splat'
status = 200
force = true

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[build]
command = 'yarn build'
publish = 'dist'